### ISSUE TITLE
Message "Non ^A Command Attempt"

### ISSUE THREAD

**Issue by TheMalwareGuardian** [sjhilt/GasPot#13]
I have deployed Gaspot, but I always get this message "Non ^A Command Attempt from: x.x.x.x" when I try to connect to it using the script atg-info.nse (nmap --script atg-info -p 10001 <host>) or telnet/ncat (telnet ip port). However, if I use the same methods against a real Guardian AST, everything works as expected so there is something strange when decoding the request.

![issue](https://user-images.githubusercontent.com/118515671/214925999-1d765b39-8828-4167-abcc-8664f281cd01.PNG)

Analyzing the source code of GasPot and the source code of Conpot related to guardian_ast, I found some issues so I have modified some lines. If anyone has the same problem, here is the commit with the changes: https://github.com/Nootropico/GasPot/commit/7ec35c40941443c14ca0b2990158e69a8f22bb95

![code](https://user-images.githubusercontent.com/118515671/214926119-8f4f1c8f-408b-4d66-8c5d-83d10c389851.PNG)

As you can see it works well when the code its updated:

![solution](https://user-images.githubusercontent.com/118515671/214926251-a584da41-524c-417f-84da-8b398d857ea5.PNG)

**Comment by sjhilt** [comment]
Awesome thanks for the update, can you do a pull request then I'll commit the change so you get credit for the update.

**Comment by TheMalwareGuardian** [comment]
Ok, done.

**Comment by sjhilt** [comment]
Fixed with merge https://github.com/sjhilt/GasPot/pull/14
