### ISSUE TITLE
When running GasPot return and OS error using Python 3.7

### ISSUE THREAD

**Issue by wildaces215** [sjhilt/GasPot#16]
```
Traceback (most recent call last):
  File "GasPot.py", line 288, in <module>
    addr = conn.getpeername()
OSError: [Errno 107] Transport endpoint is not connectet
```
In addition, I was using default config only adding addresses with the gas names.

**Comment by sjhilt** [comment]
Please upgrade your Python3 as 3.7 EOL on June 27th 2023, I tested with 3.11 on Mac, Linux and Windows and cannot replicate

**Comment by wildaces215** [comment]
Ok will do

**Comment by wildaces215** [comment]
Closed as this has been replicated
