### ISSUE TITLE
 problem to open GasPot

### ISSUE THREAD

**Issue by nexuskillerx** [sjhilt/GasPot#9]
problem to open 

\GasPot-master\GasPot.py", line 36
    print 'Please specify a configuration file or rename config.ini.dist to config.ini!'
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Please specify a configuration file or rename config.ini.dist to config.ini!')? 

I already renamed config.ini.dist to config.ini

**Comment by sjhilt** [comment]
As this is written for Python 2, I recommend using GasPot in conpot until I move it to python3. I can replicate the issues if running with Python3.

**Comment by sjhilt** [comment]
Issue solved, was easy to change code to Python3: Enjoy!
